### ISSUE TITLE
wxs 文件的代码高亮失败

### ISSUE THREAD

**Issue by naoyeye** [springlong/Sublime-wxapp#10]
![image](https://user-images.githubusercontent.com/434428/47061873-0e847a80-d206-11e8-865f-84a77ede6b6f.png)

难道是和我其他的插件冲突了吗？

**Comment by springlong** [comment]
@naoyeye 之前发布的时候，忘记给.wxs文件加上支持

你可以通过右下角将wxs文件语法文件绑定到JavaScript上即可：

![image](https://user-images.githubusercontent.com/2275225/47333231-b4c3fa80-d6b4-11e8-903f-29cdc5306d4e.png)

![image](https://user-images.githubusercontent.com/2275225/47333252-c60d0700-d6b4-11e8-986a-206087e62209.png)

**Comment by naoyeye** [comment]
以前我都是这么手动操作的。😂

**Comment by naoyeye** [comment]
我现在的办法是在 `/Users/xxxx/Library/Application Support/Sublime Text 3/Packages/User` 里新建一个文件，文件名为 `WXS.sublime-settings`，里面写：
```
{
  "extensions": ["wxs"],
  "indent_size": 2,
  "tab_size": 2,
  "translate_tabs_to_spaces": true
}

```

重启 sublime ，打开 wxs 文件，就自动识别为 js 惹。
