### ISSUE TITLE
sublime text 3176 下代码无法自动补全

### ISSUE THREAD

**Issue by henbenla** [springlong/Sublime-wxapp#4]
系统：Windows Service Pack 1
st 版本：sublime text 3176 x64

**Comment by springlong** [comment]
![image](https://user-images.githubusercontent.com/2275225/40533336-fa40998e-6034-11e8-8e60-ead8d9c9fd03.png)
需要配置下Sublime补全的触发键：[参考ReadMe中的说明](https://github.com/springlong/Sublime-wxapp#%E8%AE%BE%E7%BD%AE)

**Comment by springlong** [comment]
配置正常的话,如果wxml格式文件能高亮显示,那么自动补全应该就没有问题.
如果能高亮显示,而没有自动补全,可能与其他插件冲突或者其他配置冲突,这个我这边实在没法排查.不好意思.

**Comment by huang2a** [comment]
输入“ v ” 后有 “ view ” 的提示，但是按会车建，tab 键都都不会自动补全 “  < > ” 这两个符号，

软件版本：sublime text3 
电脑系统：mac

**Comment by springlong** [comment]
那你试一下HTML文档中, 按tab键或者enter键, 补全功能是正常的吗?

**Comment by henbenla** [comment]
为了验证是不是因为与其他插件冲突造成的问题，特意安装了 [ST 3176(x64) portable version](https://download.sublimetext.com/Sublime%20Text%20Build%203176%20x64.zip)，然后只安装 Sublime-wxapp 插件，但问题依旧存在。

![20180620_091711](https://user-images.githubusercontent.com/5373905/41632491-d1f1ac92-746c-11e8-8243-8b04b50484ff.gif)

@springlong

**Comment by henbenla** [comment]
已经进行了相关配置；输入 `<` 也是无效的。

**Comment by springlong** [comment]
按照你动图的插件安装示例，进行排查发现，你的插件是放置到 \Packages\User\ 目录下的，这样导致
 WXML_completions.py 补全提示的处理文件没有执行，故而没有补全提示。

你需要将插件安装包安装到 \Packages\ 目录下才行：
![image](https://user-images.githubusercontent.com/2275225/41669187-cd80ca68-74e3-11e8-86e2-16917654ca8e.png)

**Comment by henbenla** [comment]
确实，安装路径改了后，一切都变好了，谢谢楼主。
