### ISSUE TITLE
按enter无法换行

### ISSUE THREAD

**Issue by jacketwpbb** [springlong/Sublime-wxapp#6]
**系统mac，ST 版本3**

**情况一：**
输入view，按TAG键后自动补全后生成
`<view></view>`,此时光标在两个tag之间，按enter键无法换行
**情况二：**
输入a
出现代码提示 audio
此时按enter无法换行

**Comment by springlong** [comment]
你好：

针对情况一：
我这边Mac系统下 ST 3176版本没有测出你说的这个问题，不知道HTML文件下自动补全是否也会出现这个问题？另外是所有标签按Tab补全之后都无法按enter换行吗？按enter后是没有任何反应？

针对情况二：
你的意思是输入a之后出现提示audio，按enter自动补全了，而没有换行吗？

**Comment by jacketwpbb** [comment]
情况一：补全标签后所有标签按enter后没有反应，无法换行
情况二：没有补全，不能换行


之前html文件没有测试。
之前重启sublime也没有解决问题，今天重启后问题自己好了。。。
